spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
  hibernet:
    ddl-auto: none
    show-sql: false
      
