global:
  message: Welcome to customer serrvice dev environment
server:
  port: 8082
message: Hello from dev
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/customer_dev
    username: root
    password: MyDatabase
  jpa:
    hibernet:
      ddl-auto: update
    show-sql: true
