global:
  message: Welcome to order serrvice prod environment
server:
  port: 8085
message: Hello from order prod
spring: 
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: MyDatabase
  jpa:
    hibernet:
      ddl-auto: update
    show-sql: true
